logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: off
    jdbc: OFF
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG

spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    #show-sql: true
    properties:
      hibernate:
    #    format_sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: validate

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: oracle_jpa
    password: wndnjs123!
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy